error_404_entry: 059d4d8d-fc60-49f8-8823-7da10549e84e
copyright_name: 'Apprix Oy'
copyright_since: 2001
privacy_statement_type: none
cookie_notice_type: none
footer_description: |-
  Apprix Oy is a Finnish software company founded in 2001, providing digital
  training solutions for mid-size and large organizations. Our products include
  the Apprix Builder® authoring tool, MyCourses LMS, Checklist Engine, and
  Exam Engine.
footer_contact_title: Contact
footer_contacts:
  -
    id: mkf8krj3
    name: 'Mikko Eskelinen'
    phone: '+358 40 078 7738'
    email: mikko.eskelinen@apprix.fi
  -
    id: mkf8lgdm
    name: 'Jesse Jokinen'
    phone: '+358 40 501 9150'
    email: jesse.jokinen@apprix.fi
footer_email: etunimi.sukunimi@apprix.fi
footer_about_title: 'More about Apprix'
